backend:
  name: github
  repo: The-Good-Review/CIGL
  branch: main

media_folder: /uploads
public_folder: /uploads

collections:
  - name: accueil
    label: Accueil
    files:
      - label: Page d'accueil
        name: accueil
        file: "content/accueil.json"
        fields:
          - label: Collaborateurs
            name: collaborateurs
            widget: number

          - label: Nationalités
            name: nationalites
            widget: number

          - label: Formation
            name: "formation"
            widget: number

          - label: Années
            name: annees
            widget: number

  - name: service
    label: Service
    files:
      - label: Page de services
        name: service
        file: "content/service.json"
        fields:
          - label: Vélo
            name: velo
            widget: number

          - label: Accueil
            name: accueil
            widget: number

          - label: Désherbage
            name: desherbage
            widget: number

  - name: accompagnement
    label: Accompagnement
    files:
      - label: Page d'accompagnement
        name: accompagnement
        file: "content/accompagnement.json"
        fields:
          - label: Salaries
            name: salaries
            widget: number

          - label: Cinquantenaire
            name: cinquantenaire
            widget: number

          - label: Heures
            name: heures
            widget: number

          - label: Formations
            name: formations
            widget: number

  - name: postes
    label: Fiches de poste
    label_singular: Fiche de poste
    description: Gestion des offres d'emploi du CIGL

    folder: /content/postes
    create: true
    extension: json
    format: json

    fields:      
      - name: presentation
        label: Présentation du poste
        widget: text

      - name: missions
        label: Missions
        widget: list
        field:
          name: mission
          label: Mission
          widget: string

      - name: profil
        label: Profil recherché
        widget: list
        field:
          name: profil
          label: Profil
          widget: string

      - name: conditions
        label: Conditions
        widget: list
        field:
          name: condition
          label: Condition
          widget: string

  - name: emplois
    label: Offres d'emplois
    label_singular: Offres d'emplois
    description: Les offres d'emplois du CIGL
    extension: json
    format: json
    folder: content/emplois
    create: true

    fields:
      - name: poste
        label: Poste
        widget: string

      - name: description
        label: Description
        widget: richtext

      - name: date
        label: Date de publication
        widget: string

      - name: contrat
        label: Contrat
        widget: string

      - name: pageAssociee
        label: Page Associée
        widget: string


  - name: temoignages
    label: Témoignages
    files:
      - label: Témoignages
        name: temoignages
        file: "content/temoignages.json"
        fields:
          - label: Témoignage
            name: temTest
            widget: object
            fields:
              - label: Texte
                name: texte
                widget: text

              - label: Nom
                name: nom
                widget: string

              - label: Métier
                name: metier
                widget: string

              - label: Image
                name: img
                widget: image

  - name: actualitesGenerales
    label: Actualités générales
    label_singular: Actualité générale
    description: Gestion des actualités du CIGL
    extension: json
    format: json
    folder: content/actualitesGenerales

    create: true

    fields:
      - name: titre
        label: Titre
        widget: string

      - name: sous-titre
        label: Sous-titre
        widget: string

      - name: categorie
        label: Catégorie
        widget: select
        options:
          - vie-associative
          - projets
          - services
          - evenements

      - name: contenu
        label: Contenu
        widget: richtext

      - name: date
        label: Date de publication
        widget: string

      - name: img
        label: Image
        widget: image

  - name: famille
    label: Famille
    folder: /content/actualitesFamille/famille
    create: true
    extension: json
    format: json

    fields:
      - name: titre
        label: Titre
        widget: string

      - name: sous-titre
        label: Sous-titre
        widget: string

      - name: contenu
        label: Contenu
        widget: richtext

      - name: date
        label: Date
        widget: string

      - name: img
        label: Image
        widget: image


  - name: mobilite
    label: Mobilité
    folder: /content/actualitesFamille/mobilite
    create: true
    extension: json
    format: json

    fields:
      - name: titre
        label: Titre
        widget: string

      - name: sous-titre
        label: Sous-titre
        widget: string

      - name: contenu
        label: Contenu
        widget: richtext

      - name: date
        label: Date
        widget: string

      - name: img
        label: Image
        widget: image


  - name: jardin
    label: Jardin
    folder: /content/actualitesFamille/jardin
    create: true
    extension: json
    format: json

    fields:
      - name: titre
        label: Titre
        widget: string

      - name: sous-titre
        label: Sous-titre
        widget: string

      - name: contenu
        label: Contenu
        widget: richtext

      - name: date
        label: Date
        widget: string

      - name: img
        label: Image
        widget: image


  - name: maison
    label: Maison
    folder: /content/actualitesFamille/maison
    create: true
    extension: json
    format: json

    fields:
      - name: titre
        label: Titre
        widget: string

      - name: sous-titre
        label: Sous-titre
        widget: string

      - name: contenu
        label: Contenu
        widget: richtext

      - name: date
        label: Date
        widget: string

      - name: img
        label: Image
        widget: image


  - name: loisir
    label: Loisir
    folder: /content/actualitesFamille/loisir
    create: true
    extension: json
    format: json

    fields:
      - name: titre
        label: Titre
        widget: string

      - name: sous-titre
        label: Sous-titre
        widget: string

      - name: contenu
        label: Contenu
        widget: richtext

      - name: date
        label: Date
        widget: string

      - name: img
        label: Image
        widget: image


  - name: amenagement
    label: Aménagement
    folder: /content/actualitesFamille/amenagement
    create: true
    extension: json
    format: json

    fields:
      - name: titre
        label: Titre
        widget: string

      - name: sous-titre
        label: Sous-titre
        widget: string

      - name: contenu
        label: Contenu
        widget: richtext

      - name: date
        label: Date
        widget: string

      - name: img
        label: Image
        widget: image